services:
  postgres.db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      # - ./internal/db/migrations:/var/lib/postgresql/data/
      - postgredbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - my_network

  db.migrations:
    image: db.migrations
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: "postgresql://postgres:123456@friend-management-go-postgres.db-1:5432/postgres?sslmode=disable up"
    # volumes:
      # - ./internal/db/migrations:/migrations
    networks:
      - my_network
    depends_on:
      - postgres.db      
networks:
  my_network:
    driver: bridge
volumes:
  postgredbdata: