schema = "public"
pkgname = "models"
output = "internal/repository/models"
no-hooks = true
no-tests = true
[psql]
  dbname = "postgres"
  host = "localhost"
  port = 5432
  user = "postgres"
  password = "123456"
  sslmode = "disable"
