// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRelationships(t *testing.T) {
	t.Parallel()

	query := Relationships()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRelationshipsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRelationshipsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Relationships().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRelationshipsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RelationshipSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRelationshipsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RelationshipExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Relationship exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RelationshipExists to return true, but got false.")
	}
}

func testRelationshipsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	relationshipFound, err := FindRelationship(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if relationshipFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRelationshipsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Relationships().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRelationshipsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Relationships().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRelationshipsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	relationshipOne := &Relationship{}
	relationshipTwo := &Relationship{}
	if err = randomize.Struct(seed, relationshipOne, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}
	if err = randomize.Struct(seed, relationshipTwo, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = relationshipOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = relationshipTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Relationships().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRelationshipsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	relationshipOne := &Relationship{}
	relationshipTwo := &Relationship{}
	if err = randomize.Struct(seed, relationshipOne, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}
	if err = randomize.Struct(seed, relationshipTwo, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = relationshipOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = relationshipTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func relationshipBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func relationshipAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Relationship) error {
	*o = Relationship{}
	return nil
}

func testRelationshipsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Relationship{}
	o := &Relationship{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, relationshipDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Relationship object: %s", err)
	}

	AddRelationshipHook(boil.BeforeInsertHook, relationshipBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	relationshipBeforeInsertHooks = []RelationshipHook{}

	AddRelationshipHook(boil.AfterInsertHook, relationshipAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	relationshipAfterInsertHooks = []RelationshipHook{}

	AddRelationshipHook(boil.AfterSelectHook, relationshipAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	relationshipAfterSelectHooks = []RelationshipHook{}

	AddRelationshipHook(boil.BeforeUpdateHook, relationshipBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	relationshipBeforeUpdateHooks = []RelationshipHook{}

	AddRelationshipHook(boil.AfterUpdateHook, relationshipAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	relationshipAfterUpdateHooks = []RelationshipHook{}

	AddRelationshipHook(boil.BeforeDeleteHook, relationshipBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	relationshipBeforeDeleteHooks = []RelationshipHook{}

	AddRelationshipHook(boil.AfterDeleteHook, relationshipAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	relationshipAfterDeleteHooks = []RelationshipHook{}

	AddRelationshipHook(boil.BeforeUpsertHook, relationshipBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	relationshipBeforeUpsertHooks = []RelationshipHook{}

	AddRelationshipHook(boil.AfterUpsertHook, relationshipAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	relationshipAfterUpsertHooks = []RelationshipHook{}
}

func testRelationshipsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRelationshipsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(relationshipColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRelationshipToOneUserUsingFriend(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Relationship
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.FriendID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Friend().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := RelationshipSlice{&local}
	if err = local.L.LoadFriend(ctx, tx, false, (*[]*Relationship)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Friend == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Friend = nil
	if err = local.L.LoadFriend(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Friend == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testRelationshipToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Relationship
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, relationshipDBTypes, false, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := RelationshipSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Relationship)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testRelationshipToOneSetOpUserUsingFriend(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Relationship
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, relationshipDBTypes, false, strmangle.SetComplement(relationshipPrimaryKeyColumns, relationshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetFriend(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Friend != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.FriendRelationships[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.FriendID != x.ID {
			t.Error("foreign key was wrong value", a.FriendID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.FriendID))
		reflect.Indirect(reflect.ValueOf(&a.FriendID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.FriendID != x.ID {
			t.Error("foreign key was wrong value", a.FriendID, x.ID)
		}
	}
}
func testRelationshipToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Relationship
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, relationshipDBTypes, false, strmangle.SetComplement(relationshipPrimaryKeyColumns, relationshipColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Relationships[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testRelationshipsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRelationshipsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RelationshipSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRelationshipsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Relationships().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	relationshipDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `FriendID`: `integer`, `Status`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                   = bytes.MinRead
)

func testRelationshipsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(relationshipPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(relationshipAllColumns) == len(relationshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRelationshipsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(relationshipAllColumns) == len(relationshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Relationship{}
	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, relationshipDBTypes, true, relationshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(relationshipAllColumns, relationshipPrimaryKeyColumns) {
		fields = relationshipAllColumns
	} else {
		fields = strmangle.SetComplement(
			relationshipAllColumns,
			relationshipPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RelationshipSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRelationshipsUpsert(t *testing.T) {
	t.Parallel()

	if len(relationshipAllColumns) == len(relationshipPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Relationship{}
	if err = randomize.Struct(seed, &o, relationshipDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Relationship: %s", err)
	}

	count, err := Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, relationshipDBTypes, false, relationshipPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Relationship struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Relationship: %s", err)
	}

	count, err = Relationships().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
